### ISSUE TITLE
Info windows11 

### ISSUE THREAD

**Issue by andrea-ap** [TEKNIKGV/lanplay_manager#4]
I compiled in win11 , i run it opens client only when i insert a server , i get message in shell

![lanplay-message](https://github.com/TEKNIKGV/lanplay_manager/assets/63066393/4b020bd4-78fc-4b9f-b241-4e4a6a3af3e9)

**Comment by Decscots** [comment]
everything should still work normally

**Comment by andrea-ap** [comment]
Now execute , not have this message.

**Comment by TEKNIKGV** [comment]
Lan.teknik.app:11451 is down use joinsg.net::11453 , then maybe the error will go away, but yes everything should still work ok

**Comment by andrea-ap** [comment]
i try use joinsg.net::11453 ,but reiceve error but now connect, try if works

**Comment by Decscots** [comment]
> i try use joinsg.net::11453 ,but reiceve error but now connect, try if works
use joinsg.net:11453 ( joinsg.net::11453 but with only one ":")

**Comment by andrea-ap** [comment]
thanks, i see , i insert with only :  ,  use joinsg.net:11453 , but receive error only insert server , but see online and idle , and can connect

**Comment by andrea-ap** [comment]
![lanplay-message1](https://github.com/TEKNIKGV/lanplay_manager/assets/63066393/35b04dae-bb6f-4b35-89bf-bd9df85192e7)
![lanplay-message2](https://github.com/TEKNIKGV/lanplay_manager/assets/63066393/32a9872e-db07-4cfb-803d-9c3817b5e0c7)
